# Generated by Django 3.1.5 on 2021-02-25 13:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Dev_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('percent', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работы',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('date_received', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FlatsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx_flatris', models.CharField(max_length=10, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('section', models.IntegerField(default=0, verbose_name='секция')),
                ('property_type', models.CharField(max_length=10, verbose_name='Тип помещения')),
                ('price_m2', models.IntegerField(verbose_name='Цена за м2')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('type', models.CharField(max_length=50, verbose_name='Планировка')),
                ('square_total', models.FloatField(verbose_name='Площадь')),
                ('rooms', models.CharField(max_length=10, verbose_name='Кол-во комнат')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='flats/', verbose_name='Картинка')),
                ('img_url', models.URLField(blank=True, default=' ', null=True, verbose_name='Ссылка на картинку')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Path')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
                ('path', models.TextField(blank=True, null=True, verbose_name='Path')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, default='no name', max_length=150, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('complectation', models.CharField(blank=True, max_length=150, verbose_name='Комплектация')),
                ('pay_type', models.CharField(blank=True, choices=[('fl', '100% оплата'), ('t24', 'Рассрочка до 24 месяцев')], max_length=150, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='WidgetBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('icon', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_block', to='frontend.section')),
            ],
            options={
                'verbose_name': 'WidgetBlock',
                'verbose_name_plural': 'WidgetBlock',
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_block', to='frontend.section')),
            ],
            options={
                'verbose_name': 'ImageBlock',
                'verbose_name_plural': 'ImageBlock',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_block', to='frontend.section')),
            ],
            options={
                'verbose_name': 'HeaderBlock',
                'verbose_name_plural': 'HeaderBlock',
            },
        ),
        migrations.CreateModel(
            name='Gallery_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_images', to='frontend.documents')),
            ],
            options={
                'verbose_name': 'Галерея документов',
                'verbose_name_plural': 'Галерея документов',
            },
        ),
        migrations.CreateModel(
            name='Dev_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend.dev_category')),
            ],
            options={
                'verbose_name': 'Ход строительства',
                'verbose_name_plural': 'Ход строительства',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('advantage_mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend.advantageunit')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
