# Generated by Django 3.1.5 on 2021-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210225_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev_history',
            name='video_url',
            field=models.URLField(blank=True, default=' ', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
