# Generated by Django 3.1.5 on 2021-03-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_dev_history_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev_history',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='dev_history',
            name='photo',
        ),
    ]
