# Generated by Django 3.1.5 on 2021-03-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210303_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev_history',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dev_history',
            name='title',
        ),
    ]
