# Generated by Django 3.1.5 on 2021-03-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210303_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev_history',
            name='slug',
        ),
    ]
