# Generated by Django 3.1.5 on 2021-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_dev_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='plan_floor',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='lead',
            name='plan_number',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='lead',
            name='plan_price',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='lead',
            name='plan_section',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='lead',
            name='plan_type',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dev_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dev_history',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='dev_history',
            name='title',
            field=models.CharField(default='без названия', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flatslist',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='complectation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_name',
            field=models.CharField(blank=True, default='no name', max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('fl', '100% оплата'), ('t24', 'Рассрочка до 24 месяцев')], max_length=150, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
