# Generated by Django 3.1.5 on 2021-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_dev_history_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_history',
            name='slug',
            field=models.SlugField(default=' no slug', max_length=150),
        ),
    ]
