# Generated by Django 3.1.5 on 2021-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210304_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
